use crate::error::{Error, Result};
use crate::format::Format;
use crate::io::{fmt_f64, PcdEncoding, PcdOptions};
use crate::types::{Color, Geometry, Point, PointCloud, Vec3};
use std::io::{BufRead, Read, Write};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum DataEncoding {
    Ascii,
    Binary,
    BinaryCompressed,
}

#[derive(Debug, Clone)]
struct PcdHeader {
    fields: Vec<String>,
    size: Vec<usize>,
    ty: Vec<char>,
    count: Vec<usize>,
    width: usize,
    height: usize,
    points: usize,
    data: DataEncoding,
    comments: Vec<String>,
}

impl PcdHeader {
    fn specs(&self) -> Result<Vec<FieldSpec>> {
        if self.fields.is_empty() {
            return Err(Error::parse(Format::Pcd, None, "FIELDS header is required"));
        }
        if self.size.len() != self.fields.len()
            || self.ty.len() != self.fields.len()
            || self.count.len() != self.fields.len()
        {
            return Err(Error::parse(
                Format::Pcd,
                None,
                "FIELDS, SIZE, TYPE and COUNT must have equal lengths",
            ));
        }
        let mut offset = 0usize;
        let mut specs = Vec::with_capacity(self.fields.len());
        for idx in 0..self.fields.len() {
            let bytes = self.size[idx]
                .checked_mul(self.count[idx])
                .ok_or_else(|| Error::parse(Format::Pcd, None, "field byte size overflow"))?;
            specs.push(FieldSpec {
                name: self.fields[idx].clone(),
                size: self.size[idx],
                ty: self.ty[idx],
                count: self.count[idx],
                offset,
            });
            offset += bytes;
        }
        Ok(specs)
    }

    fn point_step(&self) -> Result<usize> {
        Ok(self
            .specs()?
            .iter()
            .map(|spec| spec.size * spec.count)
            .sum())
    }
}

#[derive(Debug, Clone)]
struct FieldSpec {
    name: String,
    size: usize,
    ty: char,
    count: usize,
    offset: usize,
}

pub fn read<R: BufRead>(reader: &mut R) -> Result<Geometry> {
    let header = read_header(reader)?;
    if header.data == DataEncoding::BinaryCompressed {
        return Err(Error::unsupported(
            Format::Pcd,
            "read",
            "binary_compressed PCD requires PCL/LZF-compatible decompression; convert to ascii/binary first or add an adapter",
        ));
    }

    let specs = header.specs()?;
    let mut cloud = PointCloud::empty();
    cloud.metadata.source_format = Some(Format::Pcd);
    cloud.metadata.point_count_hint = Some(header.points);
    cloud.metadata.comments = header.comments.clone();

    match header.data {
        DataEncoding::Ascii => read_ascii_points(reader, &header, &specs, &mut cloud)?,
        DataEncoding::Binary => read_binary_points(reader, &header, &specs, &mut cloud)?,
        DataEncoding::BinaryCompressed => {
            return Err(Error::unsupported(
                Format::Pcd,
                "read",
                "binary_compressed PCD requires PCL/LZF-compatible decompression",
            ));
        }
    }

    Ok(Geometry::PointCloud(cloud))
}

pub fn write<W: Write>(writer: &mut W, cloud: &PointCloud, options: &PcdOptions) -> Result<()> {
    let fields = write_fields(cloud);
    writeln!(
        writer,
        "# .PCD v0.7 - Point Cloud Data file generated by lidar-format-convert"
    )?;
    writeln!(writer, "VERSION 0.7")?;
    writeln!(
        writer,
        "FIELDS {}",
        fields.iter().map(|f| f.name).collect::<Vec<_>>().join(" ")
    )?;
    writeln!(
        writer,
        "SIZE {}",
        fields
            .iter()
            .map(|f| f.size.to_string())
            .collect::<Vec<_>>()
            .join(" ")
    )?;
    writeln!(
        writer,
        "TYPE {}",
        fields
            .iter()
            .map(|f| f.ty.to_string())
            .collect::<Vec<_>>()
            .join(" ")
    )?;
    writeln!(
        writer,
        "COUNT {}",
        fields
            .iter()
            .map(|f| f.count.to_string())
            .collect::<Vec<_>>()
            .join(" ")
    )?;
    writeln!(writer, "WIDTH {}", cloud.points.len())?;
    writeln!(writer, "HEIGHT 1")?;
    writeln!(writer, "VIEWPOINT 0 0 0 1 0 0 0")?;
    writeln!(writer, "POINTS {}", cloud.points.len())?;
    match options.encoding {
        PcdEncoding::Ascii => {
            writeln!(writer, "DATA ascii")?;
            write_ascii(writer, cloud, &fields, options.precision)
        }
        PcdEncoding::Binary => {
            writeln!(writer, "DATA binary")?;
            write_binary(writer, cloud, &fields)
        }
    }
}

fn read_header<R: BufRead>(reader: &mut R) -> Result<PcdHeader> {
    let mut header = PcdHeader {
        fields: Vec::new(),
        size: Vec::new(),
        ty: Vec::new(),
        count: Vec::new(),
        width: 0,
        height: 1,
        points: 0,
        data: DataEncoding::Ascii,
        comments: Vec::new(),
    };

    for line_no in 1usize.. {
        let mut line = String::new();
        if reader.read_line(&mut line)? == 0 {
            return Err(Error::parse(
                Format::Pcd,
                line_no,
                "unexpected EOF before DATA line",
            ));
        }
        let trimmed = line.trim();
        if trimmed.is_empty() {
            continue;
        }
        if trimmed.starts_with('#') {
            header
                .comments
                .push(trimmed.trim_start_matches('#').trim().to_string());
            continue;
        }
        let parts: Vec<&str> = trimmed.split_whitespace().collect();
        if parts.is_empty() {
            continue;
        }
        match parts[0].to_ascii_uppercase().as_str() {
            "VERSION" => {}
            "FIELDS" => header.fields = parts[1..].iter().map(|s| (*s).to_string()).collect(),
            "SIZE" => header.size = parse_usize_list(Format::Pcd, line_no, &parts[1..], "SIZE")?,
            "TYPE" => {
                header.ty = parts[1..]
                    .iter()
                    .map(|value| match *value {
                        "F" | "f" => Ok('F'),
                        "U" | "u" => Ok('U'),
                        "I" | "i" => Ok('I'),
                        _ => Err(Error::parse(
                            Format::Pcd,
                            line_no,
                            format!("TYPE must be F/U/I, got '{value}'"),
                        )),
                    })
                    .collect::<Result<Vec<_>>>()?;
            }
            "COUNT" => header.count = parse_usize_list(Format::Pcd, line_no, &parts[1..], "COUNT")?,
            "WIDTH" => header.width = parse_usize(Format::Pcd, line_no, parts.get(1), "WIDTH")?,
            "HEIGHT" => header.height = parse_usize(Format::Pcd, line_no, parts.get(1), "HEIGHT")?,
            "POINTS" => header.points = parse_usize(Format::Pcd, line_no, parts.get(1), "POINTS")?,
            "VIEWPOINT" => {}
            "DATA" => {
                let value = parts.get(1).ok_or_else(|| {
                    Error::parse(Format::Pcd, line_no, "DATA line requires encoding")
                })?;
                header.data = match value.to_ascii_lowercase().as_str() {
                    "ascii" => DataEncoding::Ascii,
                    "binary" => DataEncoding::Binary,
                    "binary_compressed" => DataEncoding::BinaryCompressed,
                    _ => {
                        return Err(Error::parse(
                            Format::Pcd,
                            line_no,
                            format!("unknown DATA encoding '{value}'"),
                        ))
                    }
                };
                break;
            }
            _ => {
                header.comments.push(trimmed.to_string());
            }
        }
    }

    if header.count.is_empty() {
        header.count = vec![1; header.fields.len()];
    }
    if header.points == 0 {
        header.points = header.width.saturating_mul(header.height);
    }
    if header.points == 0 {
        return Err(Error::parse(
            Format::Pcd,
            None,
            "POINTS or WIDTH/HEIGHT must be non-zero",
        ));
    }
    Ok(header)
}

fn read_ascii_points<R: BufRead>(
    reader: &mut R,
    header: &PcdHeader,
    specs: &[FieldSpec],
    cloud: &mut PointCloud,
) -> Result<()> {
    let values_per_point: usize = specs.iter().map(|spec| spec.count).sum();
    for row in 0..header.points {
        let mut line = String::new();
        if reader.read_line(&mut line)? == 0 {
            return Err(Error::parse(
                Format::Pcd,
                None,
                format!("unexpected EOF while reading point {row}"),
            ));
        }
        let values: Vec<&str> = line.split_whitespace().collect();
        if values.len() < values_per_point {
            return Err(Error::parse(
                Format::Pcd,
                None,
                format!(
                    "point {row} has {} values but {values_per_point} were expected",
                    values.len()
                ),
            ));
        }
        cloud.points.push(point_from_ascii(specs, &values)?);
    }
    Ok(())
}

fn read_binary_points<R: Read>(
    reader: &mut R,
    header: &PcdHeader,
    specs: &[FieldSpec],
    cloud: &mut PointCloud,
) -> Result<()> {
    let step = header.point_step()?;
    let mut buffer = vec![0_u8; step];
    for _ in 0..header.points {
        reader.read_exact(&mut buffer)?;
        cloud.points.push(point_from_binary(specs, &buffer)?);
    }
    Ok(())
}

fn point_from_ascii(specs: &[FieldSpec], values: &[&str]) -> Result<Point> {
    let mut index = 0usize;
    let mut scalars: Vec<(String, Scalar)> = Vec::new();
    for spec in specs {
        for count_idx in 0..spec.count {
            let name = if spec.count == 1 {
                spec.name.clone()
            } else {
                format!("{}_{count_idx}", spec.name)
            };
            let value = values.get(index).ok_or_else(|| {
                Error::parse(Format::Pcd, None, format!("missing value for field {name}"))
            })?;
            scalars.push((name, parse_scalar_text(spec, value)?));
            index += 1;
        }
    }
    point_from_scalars(&scalars)
}

fn point_from_binary(specs: &[FieldSpec], bytes: &[u8]) -> Result<Point> {
    let mut scalars: Vec<(String, Scalar)> = Vec::new();
    for spec in specs {
        for count_idx in 0..spec.count {
            let offset = spec.offset + count_idx * spec.size;
            let end = offset + spec.size;
            let name = if spec.count == 1 {
                spec.name.clone()
            } else {
                format!("{}_{count_idx}", spec.name)
            };
            scalars.push((name, parse_scalar_bytes(spec, &bytes[offset..end])?));
        }
    }
    point_from_scalars(&scalars)
}

#[derive(Debug, Clone, Copy)]
enum Scalar {
    Float(f64),
    Signed(i64),
    Unsigned(u64),
}

impl Scalar {
    fn as_f64(self) -> f64 {
        match self {
            Self::Float(v) => v,
            Self::Signed(v) => v as f64,
            Self::Unsigned(v) => v as f64,
        }
    }

    fn as_u64(self) -> Option<u64> {
        match self {
            Self::Unsigned(v) => Some(v),
            Self::Signed(v) if v >= 0 => Some(v as u64),
            Self::Float(v) if v.is_finite() && v.fract() == 0.0 && v >= 0.0 => Some(v as u64),
            _ => None,
        }
    }
}

fn point_from_scalars(scalars: &[(String, Scalar)]) -> Result<Point> {
    fn find(scalars: &[(String, Scalar)], names: &[&str]) -> Option<Scalar> {
        scalars
            .iter()
            .find(|(name, _)| {
                names
                    .iter()
                    .any(|candidate| name.eq_ignore_ascii_case(candidate))
            })
            .map(|(_, value)| *value)
    }

    let x = find(scalars, &["x"])
        .ok_or_else(|| Error::parse(Format::Pcd, None, "missing x"))?
        .as_f64();
    let y = find(scalars, &["y"])
        .ok_or_else(|| Error::parse(Format::Pcd, None, "missing y"))?
        .as_f64();
    let z = find(scalars, &["z"])
        .ok_or_else(|| Error::parse(Format::Pcd, None, "missing z"))?
        .as_f64();
    let mut point = Point::new(x, y, z);

    if let Some(intensity) = find(scalars, &["intensity", "i"]) {
        point.intensity = Some(intensity.as_f64() as f32);
    }

    let rgb = find(scalars, &["rgb", "rgba"]);
    let explicit_color = (
        find(scalars, &["red", "r"]),
        find(scalars, &["green", "g"]),
        find(scalars, &["blue", "b"]),
    );
    if let Some(rgb) = rgb {
        point.color = Some(decode_rgb(rgb));
    } else if let (Some(red), Some(green), Some(blue)) = explicit_color {
        point.color = Some(Color::new(
            scalar_to_u16(red, "red")?,
            scalar_to_u16(green, "green")?,
            scalar_to_u16(blue, "blue")?,
        ));
    }

    if let Some(classification) = find(scalars, &["classification", "class", "label"]) {
        let value = classification.as_u64().ok_or_else(|| {
            Error::parse(
                Format::Pcd,
                None,
                "classification must be a non-negative integer",
            )
        })?;
        if value > u8::MAX as u64 {
            return Err(Error::parse(
                Format::Pcd,
                None,
                "classification exceeds u8 range",
            ));
        }
        point.classification = Some(value as u8);
    }

    let normal = (
        find(scalars, &["normal_x", "nx"]),
        find(scalars, &["normal_y", "ny"]),
        find(scalars, &["normal_z", "nz"]),
    );
    if let (Some(nx), Some(ny), Some(nz)) = normal {
        point.normal = Some(Vec3::new(nx.as_f64(), ny.as_f64(), nz.as_f64()));
    }

    Ok(point)
}

fn parse_scalar_text(spec: &FieldSpec, value: &str) -> Result<Scalar> {
    match spec.ty {
        'F' => Ok(Scalar::Float(value.parse::<f64>().map_err(|_| {
            Error::parse(Format::Pcd, None, format!("invalid float '{value}'"))
        })?)),
        'U' => Ok(Scalar::Unsigned(value.parse::<u64>().map_err(|_| {
            Error::parse(
                Format::Pcd,
                None,
                format!("invalid unsigned integer '{value}'"),
            )
        })?)),
        'I' => Ok(Scalar::Signed(value.parse::<i64>().map_err(|_| {
            Error::parse(
                Format::Pcd,
                None,
                format!("invalid signed integer '{value}'"),
            )
        })?)),
        _ => Err(Error::parse(Format::Pcd, None, "unknown PCD TYPE")),
    }
}

fn parse_scalar_bytes(spec: &FieldSpec, bytes: &[u8]) -> Result<Scalar> {
    Ok(match (spec.ty, spec.size) {
        ('F', 4) => Scalar::Float(f32::from_le_bytes(array(bytes)?) as f64),
        ('F', 8) => Scalar::Float(f64::from_le_bytes(array(bytes)?)),
        ('U', 1) => Scalar::Unsigned(bytes[0] as u64),
        ('U', 2) => Scalar::Unsigned(u16::from_le_bytes(array(bytes)?) as u64),
        ('U', 4) => Scalar::Unsigned(u32::from_le_bytes(array(bytes)?) as u64),
        ('U', 8) => Scalar::Unsigned(u64::from_le_bytes(array(bytes)?)),
        ('I', 1) => Scalar::Signed(bytes[0] as i8 as i64),
        ('I', 2) => Scalar::Signed(i16::from_le_bytes(array(bytes)?) as i64),
        ('I', 4) => Scalar::Signed(i32::from_le_bytes(array(bytes)?) as i64),
        ('I', 8) => Scalar::Signed(i64::from_le_bytes(array(bytes)?)),
        _ => {
            return Err(Error::parse(
                Format::Pcd,
                None,
                format!(
                    "unsupported field TYPE/SIZE combination {}{}",
                    spec.ty, spec.size
                ),
            ))
        }
    })
}

fn array<const N: usize>(bytes: &[u8]) -> Result<[u8; N]> {
    bytes.try_into().map_err(|_| {
        Error::parse(
            Format::Pcd,
            None,
            format!("expected {N} bytes for scalar, got {}", bytes.len()),
        )
    })
}

fn scalar_to_u16(value: Scalar, name: &str) -> Result<u16> {
    let value = value.as_u64().ok_or_else(|| {
        Error::parse(
            Format::Pcd,
            None,
            format!("{name} must be a non-negative integer"),
        )
    })?;
    if value > u16::MAX as u64 {
        return Err(Error::parse(
            Format::Pcd,
            None,
            format!("{name} exceeds u16 range"),
        ));
    }
    Ok(value as u16)
}

fn decode_rgb(value: Scalar) -> Color {
    let packed = match value {
        Scalar::Float(v) => (v as f32).to_bits(),
        Scalar::Unsigned(v) => v as u32,
        Scalar::Signed(v) => v as u32,
    };
    let red = ((packed >> 16) & 0xff) as u16;
    let green = ((packed >> 8) & 0xff) as u16;
    let blue = (packed & 0xff) as u16;
    Color::new(red, green, blue)
}

#[derive(Debug, Clone, Copy)]
struct WriteField {
    name: &'static str,
    size: usize,
    ty: char,
    count: usize,
    kind: WriteFieldKind,
}

#[derive(Debug, Clone, Copy)]
enum WriteFieldKind {
    X,
    Y,
    Z,
    Intensity,
    Red,
    Green,
    Blue,
    Classification,
    NormalX,
    NormalY,
    NormalZ,
}

fn write_fields(cloud: &PointCloud) -> Vec<WriteField> {
    let mut fields = vec![
        WriteField {
            name: "x",
            size: 8,
            ty: 'F',
            count: 1,
            kind: WriteFieldKind::X,
        },
        WriteField {
            name: "y",
            size: 8,
            ty: 'F',
            count: 1,
            kind: WriteFieldKind::Y,
        },
        WriteField {
            name: "z",
            size: 8,
            ty: 'F',
            count: 1,
            kind: WriteFieldKind::Z,
        },
    ];
    if cloud.has_intensity() {
        fields.push(WriteField {
            name: "intensity",
            size: 4,
            ty: 'F',
            count: 1,
            kind: WriteFieldKind::Intensity,
        });
    }
    if cloud.has_color() {
        fields.extend([
            WriteField {
                name: "red",
                size: 2,
                ty: 'U',
                count: 1,
                kind: WriteFieldKind::Red,
            },
            WriteField {
                name: "green",
                size: 2,
                ty: 'U',
                count: 1,
                kind: WriteFieldKind::Green,
            },
            WriteField {
                name: "blue",
                size: 2,
                ty: 'U',
                count: 1,
                kind: WriteFieldKind::Blue,
            },
        ]);
    }
    if cloud.has_classification() {
        fields.push(WriteField {
            name: "classification",
            size: 1,
            ty: 'U',
            count: 1,
            kind: WriteFieldKind::Classification,
        });
    }
    if cloud.has_normals() {
        fields.extend([
            WriteField {
                name: "normal_x",
                size: 8,
                ty: 'F',
                count: 1,
                kind: WriteFieldKind::NormalX,
            },
            WriteField {
                name: "normal_y",
                size: 8,
                ty: 'F',
                count: 1,
                kind: WriteFieldKind::NormalY,
            },
            WriteField {
                name: "normal_z",
                size: 8,
                ty: 'F',
                count: 1,
                kind: WriteFieldKind::NormalZ,
            },
        ]);
    }
    fields
}

fn write_ascii<W: Write>(
    writer: &mut W,
    cloud: &PointCloud,
    fields: &[WriteField],
    precision: usize,
) -> Result<()> {
    for point in &cloud.points {
        let values: Vec<String> = fields
            .iter()
            .map(|field| field_value_text(point, field, precision))
            .collect();
        writeln!(writer, "{}", values.join(" "))?;
    }
    Ok(())
}

fn write_binary<W: Write>(writer: &mut W, cloud: &PointCloud, fields: &[WriteField]) -> Result<()> {
    for point in &cloud.points {
        for field in fields {
            write_field_binary(writer, point, field)?;
        }
    }
    Ok(())
}

fn field_value_text(point: &Point, field: &WriteField, precision: usize) -> String {
    match field.kind {
        WriteFieldKind::X => fmt_f64(point.position.x, precision),
        WriteFieldKind::Y => fmt_f64(point.position.y, precision),
        WriteFieldKind::Z => fmt_f64(point.position.z, precision),
        WriteFieldKind::Intensity => format!("{:.*}", precision, point.intensity.unwrap_or(0.0)),
        WriteFieldKind::Red => point.color.unwrap_or(Color::new(0, 0, 0)).red.to_string(),
        WriteFieldKind::Green => point.color.unwrap_or(Color::new(0, 0, 0)).green.to_string(),
        WriteFieldKind::Blue => point.color.unwrap_or(Color::new(0, 0, 0)).blue.to_string(),
        WriteFieldKind::Classification => point.classification.unwrap_or(0).to_string(),
        WriteFieldKind::NormalX => fmt_f64(point.normal.unwrap_or(Vec3::ZERO).x, precision),
        WriteFieldKind::NormalY => fmt_f64(point.normal.unwrap_or(Vec3::ZERO).y, precision),
        WriteFieldKind::NormalZ => fmt_f64(point.normal.unwrap_or(Vec3::ZERO).z, precision),
    }
}

fn write_field_binary<W: Write>(writer: &mut W, point: &Point, field: &WriteField) -> Result<()> {
    match field.kind {
        WriteFieldKind::X => writer.write_all(&point.position.x.to_le_bytes())?,
        WriteFieldKind::Y => writer.write_all(&point.position.y.to_le_bytes())?,
        WriteFieldKind::Z => writer.write_all(&point.position.z.to_le_bytes())?,
        WriteFieldKind::Intensity => {
            writer.write_all(&point.intensity.unwrap_or(0.0).to_le_bytes())?
        }
        WriteFieldKind::Red => {
            writer.write_all(&point.color.unwrap_or(Color::new(0, 0, 0)).red.to_le_bytes())?
        }
        WriteFieldKind::Green => writer.write_all(
            &point
                .color
                .unwrap_or(Color::new(0, 0, 0))
                .green
                .to_le_bytes(),
        )?,
        WriteFieldKind::Blue => writer.write_all(
            &point
                .color
                .unwrap_or(Color::new(0, 0, 0))
                .blue
                .to_le_bytes(),
        )?,
        WriteFieldKind::Classification => writer.write_all(&[point.classification.unwrap_or(0)])?,
        WriteFieldKind::NormalX => {
            writer.write_all(&point.normal.unwrap_or(Vec3::ZERO).x.to_le_bytes())?
        }
        WriteFieldKind::NormalY => {
            writer.write_all(&point.normal.unwrap_or(Vec3::ZERO).y.to_le_bytes())?
        }
        WriteFieldKind::NormalZ => {
            writer.write_all(&point.normal.unwrap_or(Vec3::ZERO).z.to_le_bytes())?
        }
    }
    Ok(())
}

fn parse_usize_list(
    format: Format,
    line: usize,
    values: &[&str],
    name: &str,
) -> Result<Vec<usize>> {
    values
        .iter()
        .map(|value| {
            value
                .parse::<usize>()
                .map_err(|_| Error::parse(format, line, format!("invalid {name} value '{value}'")))
        })
        .collect()
}

fn parse_usize(format: Format, line: usize, value: Option<&&str>, name: &str) -> Result<usize> {
    let value = value.ok_or_else(|| Error::parse(format, line, format!("missing {name}")))?;
    value
        .parse::<usize>()
        .map_err(|_| Error::parse(format, line, format!("invalid {name} '{value}'")))
}
